FROM golang:1.13.5-stretch

ADD https://github.com/operator-framework/operator-sdk/releases/download/v0.13.0/operator-sdk-v0.13.0-x86_64-linux-gnu /usr/bin/operator-sdk

RUN chmod +x /usr/bin/operator-sdk