apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: hogarama
  labels:
    prometheus: hogarama
spec:
  replicas: 1
  serviceAccountName: prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  retention: 3w
  additionalScrapeConfigs:
    name: prometheus-scrape-config
    key: scrape-config.yaml
  volumes:
    - name: prometheus-persistence
      persistentVolumeClaim:
        claimName: prometheus-pvc
        readOnly: false
  resources: 
    requests:
      memory: 128Mi
      cpu: "100m"
    limits:
      memory: 256Mi
      cpu: "200m"