kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hogarama.prometheus.storage.size }}
  storageClassName: gp2
  volumeMode: Filesystem
