apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "prometheus-db"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "prometheus-db"