kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hogarama.hogajama.mongodb.storage.size }}
#  storageClassName: gp2
  volumeMode: Filesystem
