apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: broker-amq-claim_pvc
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: null
    labels:
      app: hogarama
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-claim
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 512Mi
    volumeName: pv472-volume
  status: {}
