apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  name: hogajama-loadbalancer
  labels:
    app: hogajama
    app.kubernetes.io/component: hogajama
    app.kubernetes.io/instance: hogajama
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: hogajama
