apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hogajama-alerts
  namespace: hogarama
spec:
  groups:
    - name: alerts-sensor
      rules:
        - alert: hogarama-no-sensor
          annotations:
            description: >-
              Alle Sensoren von Hogarama haben für 1h keine Werte
              zurückgeliefert!
            summary: >-
              Von den Sensoren wurden keine neuen Sensordaten empfangen (Eine
              Stunde Messdauer)! Vermutlich ein Fehler in der Kommunikation mit
              den Habarama Clients.
          expr: 'sum(changes(hogarama_sensor_value[1h]))==0'
