kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hogajama-run
  labels:
    build: hogajama-run
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hogajama-run:latest'
  resources: 
    requests:
      memory: 1Gi
      cpu: "0.5"
    limits:
      memory: 3Gi
      cpu: "1"
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'wildfly:23.0.2.Final'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM jboss/wildfly
      COPY artefacts/deployments   /tmp/setup
      RUN /tmp/setup/configure_ocp_jboss.sh 
      RUN chgrp -R 0 /opt/jboss/wildfly && chmod g=u /opt/jboss/wildfly
    images:
      - from:
          kind: ImageStreamTag
          name: 'hogajama-build-artefacts:latest'
        as: null
        paths:
          - sourcePath: /deployments
            destinationDir: artefacts
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: 'hogajama-build-artefacts:latest'
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
