apiVersion: v1
kind: Service
metadata:
  name: hogajama-admin
  labels:
    app: hogajama
    app.kubernetes.io/component: hogajama
    app.kubernetes.io/instance: hogajama-admin
spec:
  ports:
  - name: 9990-tcp
    port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    deployment: hogajama
