apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: '2022-12-12T12:00:39Z'
  generation: 1
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:groups': {}
      manager: Mozilla
      operation: Update
      time: '2022-12-12T12:00:39Z'
  name: hogajama-alerts
  namespace: hogarama
  resourceVersion: '241431567'
  uid: 8332bfaa-6e7c-468c-8777-8da74c15c1ff
spec:
  groups:
    - name: alerts-sensor
      rules:
        - alert: hogarama-no-sensor
          annotations:
            description: Der Sensor von Hogarama hat für 10min keine Werte zurückgeliefert!
            summary: Der Sensor hat einen Fehler
          expr: 'changes(hogarama_sensor_value[10m])==0'
          for: 2m
          labels:
            severity: critical
