apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hogajama-alerts
  namespace: hogarama
spec:
  groups:
    - name: alerts-sensor
      rules:
        - alert: hogarama-no-sensor
          annotations:
            description: Der Sensor von Hogarama hat für 10min keine Werte zurückgeliefert!
            summary: Der Sensor hat einen Fehler
          expr: 'changes(hogarama_sensor_value[10m])==0'
          for: 2m
          labels:
            severity: critical
