apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hogajama-run:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hogajama-run\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: hogajama
      app.kubernetes.io/component: hogajama
      app.kubernetes.io/instance: hogajama
    name: hogajama
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: hogajama
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: hogajama
      spec:
        containers:
        - image: ' '
          name: hogajama-run
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: helm-hogajama-postgresql
          - name: AMQ_USER
            valueFrom:
              secretKeyRef:
                key: AMQ_USER
                name: amq-credentials
          - name: AMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: AMQ_PASSWORD
                name: amq-credentials
          envFrom:
            - configMapRef:
                name: hogajama-config
            - secretRef:
                name: mongodb-credentials
          resources:
            requests:
              memory: 0.5Gi
              cpu: "200m"
            limits:
              memory: 1Gi
              cpu: "1"
