kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hogajama-binary
  labels:
    build: hogajama-binary
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hogajama-binary:latest'
  resources: 
    requests:
      memory: 1Gi
      cpu: "0.5"
    limits:
      memory: 3Gi
      cpu: "1"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-builder-maven:latest'
      env:
        - name: BUILDER_CONTEXT_DIR
          value: Hogajama
        - name: BUILDER_MVN_OPTIONS
          value: '-P ocp-aws -Dfrontend.build.environment=prod'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Gepardec/Hogarama'
      ref: master
  triggers:
    - type: GitHub
      github:
        secret: {{ .Values.hogarama.hogajama.trigger.secret.hogajama_binary.github }}
    - type: Generic
      generic:
        secret: {{ .Values.hogarama.hogajama.trigger.secret.hogajama_binary.generic }}
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
