apiVersion: v1
kind: Template
metadata:
  name: hogarama-postgres
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: postgresql
      release: postgresql
      role: master
      template: hogarama-postgres
    name: data-postgresql-postgresql-0
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
