apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  ports:
    - name: 5140-tcp
      port: 5140
      protocol: TCP
      targetPort: 5140
    - name: 24224-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
  selector:
    app: fluentd
  sessionAffinity: None
  type: ClusterIP