---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: fluentd
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    helm.sh/appVersion: "{{ .Chart.AppVersion }}"
    helm.sh/revision: "{{ .Release.Revision }}"
  name: fluentd
spec:
  serviceAccount: builder
  resources:
    requests:
      memory: 400Mi
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.imageStream.name }}:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: "Dockerfile"
    dockerfile: |-
{{ .Files.Get "files/Dockerfile" | indent 6 }}
    configMaps:
      - configMap:
          name: fluentd-entrypoint
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: '{{ .Values.imageStream.base.name }}:{{ .Values.imageStream.base.tag }}'
    type: Docker
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
...