---
apiVersion: v1
data:
  MONGODB_ADMIN_PASSWORD: {{ .Values.credentials.admin.password }}
  MONGODB_DATABASE: {{ .Values.credentials.database.db }}
  MONGODB_PASSWORD: {{ .Values.credentials.database.password }}
  MONGODB_USER: {{ .Values.credentials.database.user }}
  HOGAJAMA_DB: {{ .Values.credentials.database.hogajama_db }}
  MONGODB_PW: {{ .Values.credentials.database.mongodb_pw }}
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
...