---
- name: Habarama Setup Script
  hosts: all

  tasks:
    - import_tasks: tasks/configure_network.yml
      when: setup_network


  handlers:
  - import_tasks: handlers/main.yml
...


















