---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fluentd
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    helm.sh/appVersion: "{{ .Chart.AppVersion }}"
    helm.sh/revision: "{{ .Release.Revision }}"
  name: fluentd-entrypoint
data:
{{ (.Files.Glob "files/entrypoint.sh").AsConfig | indent 2 }}
...