apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "amq-pvc"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.hogarama.amq.deploymentconfig.storage.size }}