apiVersion: v1
kind: Secret
metadata:
  name: amq-credentials
type: Opaque
data:
  AMQ_PASSWORD: {{ .Values.hogarama.amq.credentials.amq_password }}
  AMQ_USER:  {{ .Values.hogarama.amq.credentials.amq_user }}