apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: hogarama-operator
rules:
- apiGroups:
  - ""
  resources:
  - deploymentconfigs
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - routes
  - buildconfigs
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - routes
  - buildconfigs
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
    - openshift.io
  resources:
    - buildconfigs
  verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch
    - patch
- apiGroups:
    - build.openshift.io
  resources:
    - buildconfigs
  verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch
    - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apps
  resourceNames:
  - hogarama-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - hogarama.gepardec.com
  resources:
  - hogaramas
  - hogarama
  - hogarama/status
  - hogaramas/status
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
