---
postgresql:
  persistence:
    size: 1Gi
  primary:
    ## Disable security context is needed to run on OpenShift
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: "100m"
    limits:
      memory: 512Mi
      cpu: "200m"
  image:
      repository: bitnamilegacy/postgresql

...
