apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: prometheus
      type: prometheus
      url: {{ .Values.DataSource.url }}
      version: 1
      tlsSkipVerify: true
  name: grafana-datasources.yaml
