apiVersion: v1
kind: ImageStream
metadata:
  name: mongodb
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/mongodb-32-rhel7
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source

