- hosts: localhost
  gather_facts: no
  tasks:
    # Set facts for all roles and playbook executions from now on
    - name: "Set Facts"
      set_fact:
        # COMMON Part
        _label_app: "{{ name }}"
        _namespace: "{{ meta.namespace }}"
        # MONGODB Part
        _mongodb_name: "{{ name }}-mongodb"
        _mongodb_replicas: "{{ mongodb_replicas | default('1') }}"
        _mongodb_db: "hogarama-db"
        _mongodb_user: "{{ mongodb_user | default('hogarama') }}"
        _mongodb_password: "{{ mongodb_password | default('hogarama') }}"
        _mongodb_admin_password: "{{ mongodb_admin_password | default('hogarama') }}"
        _mongodb_pvc_size: "{{ mongodb_pvc_size | default('512Mi') }}"
        _mongodb_port: 27017
        _mongodb_image: "registry.access.redhat.com/rhscl/mongodb-32-rhel7:latest"
        # HOGAJAMA Part
        _hogajama_name: "{{ name }}-hogajama"
        _hogajama_replicas: "{{ hogajama_replicas | default('1') }}"
        _hogajama_git_repo: "{{ hogajama_git_repo | default('https://github.com/Gepardec/Hogarama.git') }}"
        _hogajama_git_ref: "{{ hogajama_git_ref | default('master') }}"
        _hogajama_s2i_trigger_secret_github: "{{ hogajama_s2i_trigger_secret_github | default('6dd31c017aceb946') }}"
        _hogajama_s2i_trigger_secret_generic: "{{ hogajama_s2i_trigger_secret_generic | default('a1b587899e786b0a') }}"
        _hogajama_s2i_imagestream: "{{ hogajama_s2i_imagestream | default('jboss-eap71-openshift:latest') }}"
        _hogajama_s2i_namespace: "{{ hogajama_s2i_namespace | default('openshift') }}"
        _hogajama_s2i_context_dir: "{{ hogajama_s2i_context_dir | default('Hogajama') }}"
        _hogajama_s2i_m2_url: "{{ hogajama_s2i_m2_url | default('https://nexus3-57-dev-tools.cloud.itandtel.at/repository/maven-public/') }}"
        _hogajama_s2i_m2_args: "{{ hogajama_s2i_m2_args | default('-e -Popenshift -Dcom.redhat.xpaas.repo.redhatga package -Djava.net.preferIPv4Stack=true') }}"
        _hogajama_image: "172.30.194.147:5000/57-hogarama/hogajama:production"
        _hogajama_port_web_unsecure: 8080
        _hogajama_port_web_secure: 8443
        _hogajama_port_other: 8778
        # AMQ Broker part
        _amq_name: "{{ name }}-broker"
        _amq_user: "{{ amq_user | default('amq') }}"
        _amq_password: "{{ amq_user | default('amq') }}"
        _amq_topic: "habarama"
        _amq_mqtt_ssl_port: 8883
        _amq_mqtt_port: 1883
        _amq_jolokia_port: 8778
        _amq_image_Stream: "jboss-amq-6:latest"
        _amq_storage_limit: "{{ amq_storage_limit | default('512mb')}}"
        _amq_pvc_limit: "{{ amq_pvc_limit | default('512Mi') }}"
        # Fluentd
        _fluentd_name: "{{ name }}-fluentd"_
        _fluentd_git_repo: "{{ fluentd_git_repo | default('https://github.com/Gepardec/Hogarama.git') }}"
        _fluentd_context_dir: "{{ fluentd_context_dir | default('Fluentd') }}"
        _fluentd_bc_is: "{{ fluentd_bc_is | default('fluentd-onbuild:v1.1.0-debian-onbuild') }}"
        _fluentd_bc_trigger_secret_github: "{{ fluentd_bc_trigger_secret_github | default('4m9EY9lErQRrs8LJjudP') }}"
        _fluentd_bc_trigger_secret_generic: "{{ fluentd_bc_trigger_secret_github | default('A2YAGDWxu2zgCfjIyo25') }}"
        _fluentd_5140_port: ""


    # Skip execution if mongodb_replica count is invalid
    - name: "Checking 'mongodb_replicas' setting"
      fail: "Skipping installation because {{ mongodb_replicas }} is invalid (mongodb_replicas >= 1)"
      when: mongodb_replicas < 0

    # Setup a single noe mongodb instance
    - name: "Setup mongodb '{{ _mongodb_name }}'"
      include_tasks: "roles/hogarama/tasks/mongodb_single.yml"
      when: mongodb_replicas == 1

    # Setup hogajama
    - name: "Setup hogajama '{{ _hogajama_name }}'"
      include_tasks: "roles/hogarama/tasks/hogajama.yml"
