apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: gepardec-kafka-cluster
  namespace: hogarama-kafka
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
    play.gepaplexx.com/persist: "true"
spec:
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "250m"
        limits:
          memory: 256Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "250m"
        limits:
          memory: 256Mi
          cpu: "1"
    tlsSidecar:
      resources:
        requests:
          memory: 128Mi
          cpu: "100m"
        limits:
          memory: 256Mi
          cpu: "200m"
  kafka:
    config:
      inter.broker.protocol.version: '2.6'
      log.message.format.version: '2.6'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        tls: true
        type: route
    replicas: 3
    storage:
#      class: gp2
      size: 50Gi
      type: persistent-claim
    version: 2.6.0
    resources:
      requests:
        memory: 1Gi
        cpu: "250m"
      limits:
        memory: 2Gi
        cpu: "1"
  zookeeper:
    replicas: 3
    storage:
#      class: gp2
      size: 50Gi
      type: persistent-claim
    resources:
      requests:
        memory: 256Mi
        cpu: "250m"
      limits:
        memory: 512Mi
        cpu: "1"
