---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: gepardec-kafka-cluster
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
    play.gepaplexx.com/persist: "true"
spec:
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "10m"
        limits:
          memory: 256Mi
          cpu: "300m"
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "10m"
        limits:
          memory: 256Mi
          cpu: "300m"
    tlsSidecar:
      resources:
        requests:
          memory: 128Mi
          cpu: "10m"
        limits:
          memory: 256Mi
          cpu: "300m"
  kafka:
    config:
      inter.broker.protocol.version: '3.1'
      log.message.format.version: '3.1'
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      offsets.topic.replication.factor: 1
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        tls: true
        type: route
    replicas: 1
    storage:
      size: 0.5Gi
      type: persistent-claim
    version: 3.1.0
    resources:
      requests:
        memory: 256Mi
        cpu: "10m"
      limits:
        memory: 1Gi
        cpu: "300m"
  zookeeper:
    replicas: 1
    storage:
      size: 0.5Gi
      type: persistent-claim
    resources:
      requests:
        memory: 256Mi
        cpu: "10m"
      limits:
        memory: 512Mi
        cpu: "300m"
