---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
    play.gepaplexx.com/persist: "true"
  name: gepardec-connect-cluster
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
spec:
  bootstrapServers: 'gepardec-kafka-cluster-kafka-bootstrap:9093'
  image: 'gepardec/kafka-connect-cluster:1.1.0'
  livenessProbe:
    initialDelaySeconds: 300
  replicas: 1
  config:
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  jvmOptions:
    '-Xmx': 300m
    '-Xms': 128m
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: gepardec-kafka-cluster-cluster-ca-cert
  resources:
    requests:
      memory: 256Mi
      cpu: 10m
    limits:
      memory: 512Mi
      cpu: 300m

  version: 3.1.0
