apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
    play.gepaplexx.com/persist: "true"
  name: gepardec-connect-cluster
  namespace: hogarama-kafka
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
spec:
  bootstrapServers: 'gepardec-kafka-cluster-kafka-bootstrap:9093'
  image: 'gepardec/kafka-connect-cluster:1.1.0'
  livenessProbe:
    initialDelaySeconds: 300
  replicas: 1
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: gepardec-kafka-cluster-cluster-ca-cert
  resources:
    requests:
      memory: 0.5Gi
      cpu: "250m"
    limits:
      memory: 1Gi
      cpu: "500m"

  version: 2.8.0
