---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: amq-kafka-connector
  labels:
    strimzi.io/cluster: gepardec-connect-cluster
    play.gepaplexx.com/persist: "true"
spec:
  class: org.apache.camel.kafkaconnector.sjms2.CamelSjms2SourceConnector
  config:
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    topics: habarama
    tasks.max: 1
    camel.component.sjms2.connectionFactory: org.apache.activemq.ActiveMQConnectionFactory
    camel.source.path.destinationName: habarama
    cleanup.policy: compact
    errors.log.enable: true
    camel.component.sjms2.connectionFactory.brokerURL: 'tcp://amq.hogarama.svc.cluster.local:61616'
    camel.source.path.destinationType: topic
    errors.log.include.messages: true
