---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: habarama
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
    play.gepaplexx.com/persist: "true"
spec:
  partitions: 10
  retention.ms: 604800000
  segment.bytes: 1073741824
  replicas: 1
  topicName: habarama
