apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: habarama
  namespace: hogarama-kafka
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
spec:
  partitions: 10
  retention.ms: 604800000
  segment.bytes: 1073741824
  replicas: 3
  topicName: habarama
