apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: gepardec-kafka-bridge
  namespace: hogarama-kafka
  labels:
    strimzi.io/cluster: gepardec-kafka-cluster
spec:
  bootstrapServers: 'gepardec-kafka-cluster-kafka-bootstrap:9092'
  http:
    port: 8080
  replicas: 1
