apiVersion: v1
kind: Route
metadata:
  labels:
    app: hogajama
  name: app
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: hogajama-loadbalancer
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  weight: 100
  wildcardPolicy: None