kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-builder-maven
  labels:
    build: s2i-builder-maven
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-builder-maven:latest'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'maven:3-jdk-8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/gepardec/openshift-builder-maven'
  triggers:
    - type: GitHub
      github:
        secret: {{ .Values.trigger.secret.source_to_image.github }}
    - type: Generic
      generic:
        secret: {{ .Values.trigger.secret.source_to_image.generic }}
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
