apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: broker-amq-amqp-ssl_svc
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's AMQP SSL port.
    creationTimestamp: null
    labels:
      app: hogarama
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-amqp-ssl
  spec:
    ports:
    - port: 5671
      protocol: TCP
      targetPort: 5671
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
