apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres
  name: postgresql
stringData:
  database-name: {{ .Values.database.name }}
  database-password: {{ .Values.database.password }}
  database-user: {{ .Values.database.user }}