FROM --platform=linux/amd64 registry.redhat.io/amq7/amq-broker:7.8-31.1652306076

USER root
COPY 01_create_and_run_broker.sh /
RUN chmod +x /01_create_and_run_broker.sh
CMD ["/01_create_and_run_broker.sh"]

ENTRYPOINT ["/bin/sh"]
