apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: hogarama
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's MQTT port.
      service.alpha.openshift.io/dependencies: '[{"name":"broker-amq-mqtt-ssl","namespace":"","kind":"Service"}]'
    creationTimestamp: null
    labels:
      app: amq62-persistent-ssl
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-mqtt
  spec:
    ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's MQTT SSL port.
    creationTimestamp: null
    labels:
      app: amq62-persistent-ssl
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-mqtt-ssl
  spec:
    ports:
    - port: 8883
      protocol: TCP
      targetPort: 8883
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: fluentd
    name: fluentd
  spec:
    ports:
    - name: 5140-tcp
      port: 5140
      protocol: TCP
      targetPort: 5140
    - name: 24224-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
    selector:
      app: fluentd
      deploymentconfig: fluentd
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: hogajama
    name: hogajama
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: hogajama
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: mongodb-persistent
      template: mongodb-persistent-template
    name: mongodb
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: amq62-persistent-ssl
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq
  spec:
    replicas: 1
    selector:
      deploymentConfig: broker-amq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: broker
          deploymentConfig: broker-amq
        name: broker-amq
      spec:
        containers:
        - env:
          - name: AMQ_USER
            value: mq_habarama
          - name: AMQ_PASSWORD
            value: ${MQ_HABARAMA_PASS}
          - name: AMQ_TRANSPORTS
            value: mqtt
          - name: AMQ_QUEUES
          - name: AMQ_TOPICS
            value: habarama
          - name: MQ_SERIALIZABLE_PACKAGES
          - name: AMQ_SPLIT
            value: "false"
          - name: AMQ_MESH_DISCOVERY_TYPE
            value: kube
          - name: AMQ_MESH_SERVICE_NAME
            value: broker-amq-tcp
          - name: AMQ_MESH_SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: AMQ_KEYSTORE_TRUSTSTORE_DIR
            value: /etc/amq-secret-volume
          - name: AMQ_TRUSTSTORE
            value: broker.ks
          - name: AMQ_TRUSTSTORE_PASSWORD
            value: L(o?cqGPtJ}7YiHu
          - name: AMQ_KEYSTORE
            value: broker.ks
          - name: AMQ_KEYSTORE_PASSWORD
            value: L(o?cqGPtJ}7YiHu
          - name: AMQ_STORAGE_USAGE_LIMIT
            value: 1 gb
          image: registry.access.redhat.com/jboss-amq-6/amq62-openshift@sha256:acadeae82790e144cc8631db9a78344cad2b359bc46d463a556c77caf08b11be
          imagePullPolicy: Always
          name: broker-amq
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 5671
            name: amqp-ssl
            protocol: TCP
          - containerPort: 1883
            name: mqtt
            protocol: TCP
          - containerPort: 8883
            name: mqtt-ssl
            protocol: TCP
          - containerPort: 61613
            name: stomp
            protocol: TCP
          - containerPort: 61612
            name: stomp-ssl
            protocol: TCP
          - containerPort: 61616
            name: tcp
            protocol: TCP
          - containerPort: 61617
            name: tcp-ssl
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/amq/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /etc/amq-secret-volume
            name: broker-secret-volume
            readOnly: true
          - mountPath: /opt/amq/data
            name: broker-amq-pvol
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
        volumes:
        - name: broker-secret-volume
          secret:
            defaultMode: 420
            secretName: amq-app-secret
        - name: broker-amq-pvol
          persistentVolumeClaim:
            claimName: broker-amq-claim
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - broker-amq
        from:
          kind: ImageStreamTag
          name: jboss-amq-62:1.3
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: fluentd
    name: fluentd
  spec:
    replicas: 1
    selector:
      app: fluentd
      deploymentconfig: fluentd
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.fluentd.image.entrypoint: '["/bin/bash"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: fluentd
          deploymentconfig: fluentd
      spec:
        containers: 
        - image: 172.30.194.147:5000/57-hogarama/fluentd:production
          imagePullPolicy: Always
          name: fluentd
          ports:
          - containerPort: 24224
            protocol: TCP
          - containerPort: 5140
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /fluentd/log
            name: fluentd-log-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: fluentd-log-volume
          persistentVolumeClaim:
            claimName: fluentd-log-claim
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - fluentd
        from:
          kind: ImageStreamTag
          name: fluentd:latest
          namespace: 57-hogarama
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: hogajama
    name: hogajama
  spec:
    replicas: 1
    selector:
      deploymentconfig: hogajama
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hogajama
          deploymentconfig: hogajama
      spec:
        containers:
        - env:
          - name: STAGE
            value: ${STAGE}
          - name: MONGODB_PW
            value: ${MONGODB_PASSWORD}
          - name: OPENSHIFT_AUTH_TOKEN
            value: ${OPENSHIFT_AUTH_TOKEN}
          - name: TINYURL
            value: ${TINYURL}
          - name: CURRENT_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: 172.30.194.147:5000/57-hogarama/hogajama:production
          imagePullPolicy: Always
          name: hogajama
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /hogajama-charts.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1

          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - hogajama
        from:
          kind: ImageStreamTag
          name: hogajama:latest
          namespace: 57-hogarama
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: mongodb-persistent
      template: mongodb-persistent-template
    name: mongodb
  spec:
    replicas: 1
    selector:
      name: mongodb
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: mongodb
      spec:
        containers:
        - env:
          - name: MONGODB_USER
            value: hogajama
          - name: MONGODB_PASSWORD
            value: ${MONGODB_PASSWORD} 
          - name: MONGODB_DATABASE
            value: hogajamadb
          - name: MONGODB_ADMIN_PASSWORD
            value: ${MONGODB_ADMIN_PASSWORD} 
          image: registry.access.redhat.com/rhscl/mongodb-32-rhel7@sha256:4143584de718ef477fe03e3ae15985c68e0ce9dca8ba089dfa5927e800e59e69
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      app: amq62-persistent-ssl
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-claim
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 512Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: fluentd-log-claim
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      app: mongodb-persistent
      template: mongodb-persistent-template
    name: mongodb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: amq62-persistent-ssl
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-mqtt-ssl
  spec:
    tls:
      termination: passthrough
    to:
      kind: Service
      name: broker-amq-mqtt-ssl
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: hogajama
    name: hogajama
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: hogajama
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: hogajama
    name: hogajama-ssl
  spec:
    port:
      targetPort: 8443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: hogajama
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  data:
    broker.ks: /u3+7QAAAAIAAAABAAAAAQAGYnJva2VyAAABXUDOp6QAAAUBMIIE/TAOBgorBgEEASoCEQEBBQAEggTp2UzQ7GRkCOp1+J52iehxoH8WzHmTJaqB3nv/ijJ6mji15Kr7G7PS7FJq4xR1CQYhhrkKUWSgDMTchX6YuXMAxQU4bKBx4N53UzxHMLbkiMpvGG9IBvWQSGWY43H9lrCjyP3ltf8xx5f8vlHvawvVicaFrQOeYLLa2mQwjXo7jm8Nivp5t7WXtqqpCyDjVVKmlEeo5m5D1ELTu/AgeJGPQd8FOb71crXZIP1jAaKKMiDIwu1Bf4vIko8lew6zl4/Mel1Vy5pBnJjl1Thdt9OLsDgiBv4IrvdXf8JxRV8EWDZMEroTwyz1Mle59tn3xj7xIhCkNaAxOGlTHiWS8/qG/hstsYli6Li/WDJGHLDzcwXjqL1EQeOEvAUvQXc8/7YhxxtN/di0caIwx1r6a37yKsHD2QssO1bHQAPmmRyzeJPEClE3xkwzaqV5DpHXM713zuf2SWDRGjIBX6LH15zovfx/mNBkXb3l0YC1KqEtj05akUnLioyV/RGGcG2CzfYB85wV8KIeRm92kTajARIu3l4n7SVCQzFCYF26ShNSOR2KYNrCD6ZrjmxZjAptLHngitKMbA3i7Om+J/GCGlN1WwR14kqZZXdrBN7vAxxtMo2bJE5upz7M26sV7BfaR8sikUmU2mt7gNepESMy5RkH2s6h01TjLuR9eqh1QdydBmKBabtp6gNWq4FTCFz8bCXEvcID3qJP5vqyB73kp+SZdYc9u8eShBdQ/mbBf/H24dcADBXSJpjycRPsBY0J1bl0DBrBoaOVK/we1DXppM/twGylPONdt1+wDY1FyiozYzygmg8Dxc7c/hNshUVNy4VyHvC2HG1c1lqi09hDLHcHpDPqFg4YAD+DsNYkt8ROly7wqiWYjJ7oJ+nb5hDTEfVu7AFChv5Ws38OaXAN2+yLt0aVNuZc1yzElGaIgzFAPo1g1EVpxnBYXpy88TA6OAEKnXaIETWiU9cAccdU3Mdn9Jkk4P+FD7KiSytTm11rYh3RQoTU3rdZXdB1cWe58sNFoP8p75Uvf5LAhujWi/ggX/oS4AcmFDtpQKbZ5jFHjQuCGfRGauQBfyIPBRBYNkoq2UNXlxWkZICKSoznVT/YCKLHAfi09GBAhcU4h9k6zoqDfpsAg+aLac+4ojyJWeu4qh/2OzXuV0WVQdR/NyQBVwWGeH98NigBvOdNSgkfVQSHBP3l8/s+iovvba6GG8kHUNVpc+S6R133XpLKAgXwBB5KBXxmxl8EYoc/ZTanvGTssL+1ijSCS1UIvnSlXmQsS1CYdPN7ZFakl1II5zdLFwsVNXVeP7Ouq0OzZXQVyypnYQCm4K11nhWwBROD42Jhkj6fsbUEowVB3RxjWgk4DLeITswFJOBcMJwyvIDI3Cte812ZnCbwVF3jx/dWMflt4KulDgRPQ4rZEQmyS90qwap4/6UJjwlB+y0+j7Z8PTEI6f1EPFKtm0Z4YY6vl3QDyRCor5D9xCjEKAWnbtb92hFsUWxeujPzU6SuSO4IBQCOLY9nqDFqaMLNbGkzxmvy3gPN7VGehOcXDtqI+pmq67W2uFu5EeXS2xR7OXiA8d10j4rP3+Zp3kbQxCDZ6TUgizmKJfDx4FcBx9cexsmVUzSRNTwk91sppuVbWTSBnRDwRe134Axmp8YmLpPc/wCAXtw/K8BOJpA3AAAAAQAFWC41MDkAAAN/MIIDezCCAmOgAwIBAgIEEjSguDANBgkqhkiG9w0BAQsFADBtMRAwDgYDVQQGEwdVbmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMREwDwYDVQQKEwhHZXBhcmRlYzEQMA4GA1UECxMHVW5rbm93bjEQMA4GA1UEAxMHVW5rbm93bjAgFw0xNzA3MTQxMTE0MjhaGA8yMTE3MDYyMDExMTQyOFowbTEQMA4GA1UEBhMHVW5rbm93bjEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjERMA8GA1UEChMIR2VwYXJkZWMxEDAOBgNVBAsTB1Vua25vd24xEDAOBgNVBAMTB1Vua25vd24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCESfv9drqJUjIt8q5tA8xvpd1yjsBNCUv9EMnhA4B49nKs1el7BWcekHbZhiJrBoExVUoFbfDKArPDiQK1bFbNrpjkKso4Z7zU/vdhhQ9VetoJMom8tuhsrX1ZE4xwMzsJmUmCO/3XyVYc/b7xCzD9W6ys+dJGy8GAI3MMaFFBdCWjUnv5PwoU1BkEBqxjabjxhymLLXd0c9HmZBb7X8VhkhJfyZIKxvb7mjKYri2SIm9BF9B8tzf7wHmMX+vd4TtKyir2XkmLeWX2EhhYkIKAj3h6sd3KYiK2n7h8dm+70q4/Eu7E6ttCwYp/aXnEA3GGs9VVVodKK0k1yJ9ByFGjAgMBAAGjITAfMB0GA1UdDgQWBBQ1S3GHrfC3TmV2Ok9gbMg1VIFhiTANBgkqhkiG9w0BAQsFAAOCAQEAZDigAJWTSaM+TSyA9jgIID48QGdk7qBDPSPE+1sbZDZlL/dAzeHnSNjs2x9uEoyBiR5AhlAVzfMPX3UpZ1uyrPiXzWRqktkPXF1Kr/RcLZVpOJ/NhhU6fDM8yJkjeCsPCKfwdKccJ4K/Ge/CV0Lz5yLTTy/RwfvSpGU9uB+8WDTN1pyGXLtOzT1ZC/iAQsrE2BZuRmfqyz2pNEWXwfiyxp7/2Qu3e4O62W7apuuVuhzqfK0NcE2sBqQ5T3yEgFfT3wQJ4F9sOeIneW7LrYl2X0aFNKqb6thgxdJx92jfG8qtaD08Ehkjz1+/cLWukE2Oftz4dMEbZpsKRO+/T4JTEMZ7kJh3lm5VtEKrvl7UHmx0/FDS
  kind: Secret
  metadata:
    creationTimestamp: null
    name: amq-app-secret
  type: Opaque
parameters:
    - description: Stage of this project
      from: '[A-Z0-9]{8}'
      value: test
      name: STAGE
    - description: Password used for MQ authentication
      from: '[A-Z0-9]{8}'
      value: mq_habarama_pass
      name: MQ_HABARAMA_PASS
    - description: Password used for MongoDB User authentication
      from: '[A-Z0-9]{8}'
      value: hogajama@mongodb
      name: MONGODB_PASSWORD
    - description: Password used for MongoDB Admin authentication
      from: '[A-Z0-9]{8}'
      generate: expression
      name: MONGODB_ADMIN_PASSWORD
    - description: Session token
      from: '[A-Z0-9]{8}'
      name: OPENSHIFT_AUTH_TOKEN
    - description: Tiny URL
      from: '[A-Z0-9]{8}'
      name: TINYURL

