apiVersion: v1
kind: ImageStream
metadata:
  generation: 1
  name: grafana
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: grafana/grafana:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source