apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: hogarama-jboss
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: hogajama
      template: hogarama-jboss
    name: hogajama
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hogajama:tested
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: Hogajama
      git:
        ref: ${BRANCH}
        uri: https://github.com/Gepardec/Hogarama.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS
          value: -e -Popenshift -Dcom.redhat.xpaas.repo.redhatga package -Djava.net.preferIPv4Stack=true
        from:
          kind: ImageStreamTag
          name: jboss-eap71-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 6dd31c017aceb946
      type: GitHub
    - generic:
        secret: a1b587899e786b0a
      type: Generic
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: hogajama
      template: hogarama-jboss
    name: hogajama
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: hogajama
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: hogajama
      template: hogarama-jboss
    name: hogajama
  spec:
    replicas: 1
    selector:
      deploymentconfig: hogajama
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hogajama
          deploymentconfig: hogajama
      spec:
        containers:
        - env:
          - name: STAGE
            value: ${STAGE}
          - name: MONGODB_PW
            value: ${MONGODB_PASSWORD}
          - name: OPENSHIFT_AUTH_TOKEN
            value: ${OPENSHIFT_AUTH_TOKEN}
          - name: TINYURL
            value: ${TINYURL}
          - name: KEYCLOAK_AUTH_SERVER_URL
            value: ${KEYCLOAK_AUTH_SERVER_URL}
          - name: POSTGRESQL_DATABASE
            value: units
          - name: POSTGRESQL_USER
            value: hogarama
          - name: POSTGRESQL_PASSWORD
            value: changepassword
          - name: CURRENT_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_OPTS
            value: >-
              -Xms128m -Xmx128m -XX:MaxMetaspaceSize=96m
              -Djava.net.preferIPv4Stack=true
              -Djboss.modules.system.pkgs=org.jboss.logmanager,jdk.nashorn.api,com.sun.crypto.provider
              -Djava.awt.headless=true
          image: hogarama/hogajama
          imagePullPolicy: Always
          name: hogajama
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /hogajama-charts.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - hogajama
        from:
          kind: ImageStreamTag
          name: hogajama:tested
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: hogajama
      template: hogarama-jboss
    name: hogajama
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: hogajama
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: hogajama
      template: hogarama-jboss
    name: hogajama-ssl
  spec:
    port:
      targetPort: 8443-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: hogajama
      weight: 100
    wildcardPolicy: None
parameters:
    - description: Stage of this project
      from: '[A-Z0-9]{8}'
      value: test
      name: STAGE
    - description: Password used for MQ authentication
      from: '[A-Z0-9]{8}'
      value: mq_habarama_pass
      name: MQ_HABARAMA_PASS
    - description: Password used for MongoDB User authentication
      from: '[A-Z0-9]{8}'
      value: hogajama@mongodb
      name: MONGODB_PASSWORD
    - description: Password used for MongoDB Admin authentication
      from: '[A-Z0-9]{8}'
      generate: expression
      name: MONGODB_ADMIN_PASSWORD
    - description: Session token
      from: '[A-Z0-9]{8}'
      name: OPENSHIFT_AUTH_TOKEN
    - description: Tiny URL
      from: '[A-Z0-9]{8}'
      name: TINYURL
    - description: Url of SSO authentication server
      value: https://secure-sso-57-hogarama.cloud.itandtel.at/auth/
      name: KEYCLOAK_AUTH_SERVER_URL
    - description: Branch for Builds
      from: '[A-Z0-9]{8}'
      value: master
      name: BRANCH
