apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: broker-amq-tcp_svc
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's OpenWire port.
      service.alpha.openshift.io/dependencies: '[{"name":"broker-amq-tcp-ssl","namespace":"","kind":"Service"}]'
    creationTimestamp: null
    labels:
      app: hogarama
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-tcp
  spec:
    ports:
    - port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
