apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: broker-amq-stomp_svc
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's STOMP port.
      service.alpha.openshift.io/dependencies: '[{"name":"broker-amq-stomp-ssl","namespace":"","kind":"Service"}]'
    creationTimestamp: null
    labels:
      app: hogarama
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-stomp
  spec:
    ports:
    - port: 61613
      protocol: TCP
      targetPort: 61613
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
