apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: broker-amq-mqtt-ssl_svc
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The broker's MQTT SSL port.
    creationTimestamp: null
    labels:
      app: hogarama
      application: broker
      template: amq62-persistent-ssl
      xpaas: 1.3.1
    name: broker-amq-mqtt-ssl
  spec:
    ports:
    - port: 8883
      protocol: TCP
      targetPort: 8883
    selector:
      deploymentConfig: broker-amq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
