apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-secret-hogarama
  labels:
    app: sso
spec:
  client:
    clientAuthenticatorType: client-secret
    id: "hogarama"
    clientId: "hogarama"
    protocol: "openid-connect"
    baseUrl: "/auth/realms/gepardec/hogarama"
    secret: "{{ .Values.keycloak.client.secret }}"
    redirectUris: ["*"]
    identityProvider: google
  realmSelector:
    matchLabels:
      app: sso