apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: hogarama-client
  labels:
    app: sso
spec:
  client:
    clientAuthenticatorType: client-secret
    id: "hogarama"
    clientId: "hogarama"
    protocol: "openid-connect"
    baseUrl: "/auth/realms/gepardec/hogarama"
    secret: "{{ .Values.keycloak.client.secret }}"
    defaultClientScopes:
    - microprofile-jwt
    - roles
    redirectUris: ["*"]
    webOrigins: ["*"]
#    identityProvider: google
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
  realmSelector:
    matchLabels:
      app: sso
  roles:
    - clientRole: false
      description: Hogarama Administratoren
      name: admins3

