apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: aws-ocp-keycloak
  labels:
    app: sso
spec:
  instances: 1
  extensions:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    resources:
      limits:
        cpu: '1'
        memory: '1024Mi'
      requests:
        cpu: '100m'
        memory: '512Mi'
    livenessProbe:
      initialDelaySeconds: 300
  postgresDeploymentSpec:
    resources:
      limits:
        cpu: '200m'
        memory: '512Mi'
      requests:
        cpu: '100m'
        memory: '256Mi'
