apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 1Gi
        cpu: 1
      defaultRequest:
        memory: 512Mi
        cpu: 500m
      type: Container