apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: gepardec
  labels:
    app: sso
spec:
  realm:
    id: hogarama
    realm: hogarama
    enabled: true
    displayName: hogarama
    roles:
      realm:
      - clientRole: false
        composite: false
        containerId: hogarama
        description: Hogarama Admins
        name: admins
    users:
    - credentials:
      - type: password
        value: {{ .Values.keycloak.users.jamal.password }}
      email: jamal@gepard.com
      enabled: true
      firstName: Jamal
      lastName: Gepard
      username: jamal
      realmRoles:
      - admins
    identityProviders: [
      {
        "providerId": "google",
        "displayName": "Google",
        "enabled": true,
        "alias": "google",
        "config": {
          "alias": "google",
          "clientId": "{{ .Values.keycloak.google.client.id }}",
          "clientSecret": "{{ .Values.keycloak.google.client.secret }}"
        }
      }
      ]
  instanceSelector:
    matchLabels:
      app: sso
  unmanaged: false
