apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eap-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: eap
  source: redhat-operators
  sourceNamespace: openshift-marketplace
#  version: 1.0.0
  config:
    resources: 
      requests:
        memory: 128Mi
        cpu: "100m"
      limits:
        memory: 256Mi
        cpu: "200m"