apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Manual
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    resources: 
      requests:
        memory: 128Mi
        cpu: "100m"
      limits:
        memory: 256Mi
        cpu: "200m"