---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.logrotate default variables [[[
# ======================================

# .. contents:: Sections
#    :local:
#
# .. include:: includes/all.rst


# Global configuration [[[
# ------------------------

# .. envvar:: logrotate__enabled [[[
#
# Enable or disable management of ``logrotate`` configuration files.
logrotate__enabled: True

                                                                   # ]]]
# .. envvar:: logrotate__base_packages [[[
#
# List of base APT packages to install.
logrotate__base_packages: [ 'logrotate', 'cron' ]

                                                                   # ]]]
# .. envvar:: logrotate__packages [[[
#
# List of additional APT packages to install with ``logrotate``.
logrotate__packages: []

                                                                   # ]]]
# .. envvar:: logrotate__cron_period [[[
#
# Specify how often :program:`cron` should execute log rotation. By default the
# ``logrotate`` command will be executed daily. Available periods are:
# ``hourly``, ``daily``, ``weekly``, ``monthly``.
logrotate__cron_period: 'daily'

                                                                   # ]]]
# .. envvar:: logrotate__default_period [[[
#
# Select the default log rotation period. Supported values are: ``daily``,
# ``weekly``, ``monthly``, ``yearly``. The ``logrotate`` command is currently
# run daily via a :program:`cron` script.
logrotate__default_period: 'daily'

                                                                   # ]]]
# .. envvar:: logrotate__default_rotation [[[
#
# Specify the number of old log files to keep before removing them.
logrotate__default_rotation: '7'

                                                                   # ]]]
# .. envvar:: logrotate__options [[[
#
# A YAML text block with ``logrotate`` options configured in the main
# configuration file for all hosts in the inventory.
logrotate__options: ''

                                                                   # ]]]
# .. envvar:: logrotate__group_options [[[
#
# A YAML text block with ``logrotate`` options configured in the main
# configuration file for hosts in specific groups.
logrotate__group_options: ''

                                                                   # ]]]
# .. envvar:: logrotate__host_options [[[
#
# A YAML text block with ``logrotate`` options configured in the main
# configuration file for specific hosts in the inventory.
logrotate__host_options: ''

                                                                   # ]]]
# .. envvar:: logrotate__default_options [[[
#
# A YAML text block with ``logrotate`` configuration options applied to all
# logs by default. These options will be applied last, the last line should
# include other configuration files located in :file:`/etc/logrotate.d/` directory.
# orig:
#  create
#  {{ logrotate__default_period }}
#  rotate {{ logrotate__default_rotation }}
#  tabooext + .dpkg-divert
#  include /etc/logrotate.d
logrotate__default_options: |
  # create new (empty) log files after rotating old ones
  create

  # see "man logrotate" for details
  # rotate log files
  {{ logrotate__default_period }}

  # keep 4 weeks worth of backlogs
  rotate {{ logrotate__default_rotation }}

  # copied from https://github.com/debops/ansible-logrotate/
  tabooext + .dpkg-divert

  # uncomment this if you want your log files compressed
  #compress

  # packages drop log rotation information into this directory
  include /etc/logrotate.d

# ]]]
# ]]]
# Log rotation configuration [[[
# ------------------------------

# .. envvar:: logrotate__default_config [[[
#
# Configuration of log rotation for logs that don't have their own packaged
# configuration in :file:`/etc/logrotate.d/`. This configuration will be included
# in the main ``logrotate`` configuration file. See :ref:`logrotate__config`
# for more details about the syntax.
logrotate__default_config:

  - log: '/var/log/wtmp'
    comment: 'No packages own wtmp or btmp, they will be managed directly'
    options: |
      missingok
      monthly
      create 0664 root utmp
      rotate 1

  - log: '/var/log/btmp'
    options: |
      missingok
      monthly
      create 0660 root utmp
      rotate 1

# ]]]
# .. envvar:: logrotate__config [[[
#
# Log rotation configuration for all hosts in Ansible inventory. See
# :ref:`logrotate__config` for more details.
logrotate__config:

  - filename: 'rsyslog'
    #log: '/var/log/syslog'
    #state: 'present'
    options: |
      /var/log/syslog
      {
              rotate {{ logrotate__default_rotation }}
              {{ logrotate__default_period }}
              missingok
              notifempty
              delaycompress
              compress
              postrotate
                      invoke-rc.d rsyslog rotate > /dev/null
              endscript
      }

      /var/log/mail.info
      /var/log/mail.warn
      /var/log/mail.err
      /var/log/mail.log
      /var/log/daemon.log
      /var/log/kern.log
      /var/log/auth.log
      /var/log/user.log
      /var/log/lpr.log
      /var/log/cron.log
      /var/log/debug
      /var/log/messages
      {
              rotate {{ logrotate__default_rotation }}
              {{ logrotate__default_period }}
              missingok
              notifempty
              compress
              delaycompress
              sharedscripts
              postrotate
                      invoke-rc.d rsyslog rotate > /dev/null
              endscript
      }

# ]]]
# .. envvar:: logrotate__group_config [[[
#
# Log rotation configuration for hosts in a specific Ansible group. See
# :ref:`logrotate__config` for more details.
logrotate__group_config: []

                                                                   # ]]]
# .. envvar:: logrotate__host_config [[[
#
# Log rotation configuration for specific hosts in Ansible inventory. See
# :ref:`logrotate__config` for more details.
logrotate__host_config: []

                                                                   # ]]]
# .. envvar:: logrotate__dependent_config [[[
#
# Log rotation configuration defined by other Ansible roles through dependent
# variables. See :ref:`logrotate__config` for more details.
logrotate__dependent_config: []
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
