---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amq
  name: amq
spec:
  ports:
    - name: 61616-tcp
      port: 61616
      protocol: TCP
      targetPort: 61616
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 61613-tcp
      port: 61613
      protocol: TCP
      targetPort: 61613
    - name: 5445-tcp
      port: 5445
      protocol: TCP
      targetPort: 5445
    - name: 1883-tcp
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: 8883-tcp
      port: 8883
      protocol: TCP
      targetPort: 8883
    - name: 8161-tcp
      port: 8161
      protocol: TCP
      targetPort: 8161
  selector:
    deploymentconfig: amq
  sessionAffinity: None
  type: ClusterIP
...