FROM fedora:latest

ARG SETUP=/tmp/setup
ARG ENV_FILE=hogarama_local.env

RUN mkdir -p $SETUP
ADD bin configs $SETUP/
ADD local_env/$ENV_FILE $SETUP/local_env/$ENV_FILE

RUN yum -y update && \
    yum -y clean all && \
    yum -y install java-1.8.0-openjdk &&  \
    yum -y install unzip &&  \
    yum -y install git && \
    yum -y install wget && \
    mkdir /root/Downloads && \
    sudo wget -c https://github.com/wildfly/wildfly/releases/download/26.1.1.Final/wildfly-26.1.1.Final.zip -P /root/Downloads/

USER 0
RUN chmod a+x $SETUP/setup.sh &&  \
    $SETUP/setup.sh

ENTRYPOINT ["/bin/sh"]
